<?php 
    include ('/home/tgorczynski1/public_html/dmit2025/includes-site/header.php');

?>

<p>WE had now reached the summit of the loftiest crag. For some minutes the old man seemed too much exhausted to speak.</p>

<p>"Not long ago," said he at length, "and I could have guided you on this route as well as the youngest of my sons ; but, about three years past, there happened to me an event such as never happened to mortal man -- or at least such as no man ever survived to tell of -- and the six hours of deadly terror which I then endured have broken me up body and soul. You suppose me a very old man -- but I am not. It took less than a single day to change these hairs from a jetty black to white, to weaken my limbs, and to unstring my nerves, so that I tremble at the least exertion, and am frightened at a shadow. Do you know I can scarcely look over this little cliff without getting giddy ?"</p>

<p>The "little cliff," upon whose edge he had so carelessly thrown himself down to rest that the weightier portion of his body hung over it, while he was only kept from falling by the tenure of his elbow on its extreme and slippery edge -- this "little cliff" arose, a sheer unobstructed precipice of black shining rock, some fifteen or sixteen hundred feet from the world of crags beneath us. Nothing would have tempted me to within half a dozen yards of its brink. In truth so deeply was I excited by the perilous position of my companion, that I fell at full length upon the ground, clung to the shrubs around me, and dared not even glance upward at the sky -- while I struggled in vain to divest myself of the idea that the very foundations of the mountain were in danger from the fury of the winds. It was long before I could reason myself into sufficient courage to sit up and look out into the distance.</p>

<p>"You must get over these fancies," said the guide, "for I have brought you here that you might have the best possible view of the scene of that event I mentioned -- and to tell you the whole story with the spot just under your eye."</p>

<p>"We are now," he continued, in that particularizing manner which distinguished him -- "we are now close upon the Norwegian coast -- in the sixty-eighth degree of latitude -- in the great province of Nordland -- and in the dreary district of Lofoden. The mountain upon whose top we sit is Helseggen, the Cloudy. Now raise yourself up a little higher -- hold on to the grass if you feel giddy -- so -- and look out, beyond the belt of vapor beneath us, into the sea."</p>

<p>I looked dizzily, and beheld a wide expanse of ocean, whose waters wore so inky a hue as to bring at once to my mind the Nubian geographer's account of the Mare Tenebrarum. A panorama more deplorably desolate no human imagination can conceive. To the right and left, as far as the eye could reach, there lay outstretched, like ramparts of the world, lines of horridly black and beetling cliff, whose character of gloom was but the more forcibly illustrated by the surf which reared high up against its white and ghastly crest, howling and shrieking forever. Just opposite the promontory upon whose apex we were placed, and at a distance of some five or six miles out at sea, there was visible a small, bleak-looking island ; or, more properly, its position was discernible through the wilderness of surge in which it was enveloped. About two miles nearer the land, arose another of smaller size, hideously craggy and barren, and encompassed at various intervals by a cluster of dark rocks.</p>

<p>The appearance of the ocean, in the space between the more distant island and the shore, had something very unusual about it. Although, at the time, so strong a gale was blowing landward that a brig in the remote offing lay to under a double-reefed trysail, and constantly plunged her whole hull out of sight, still there was here nothing like a regular swell, but only a short, quick, angry cross dashing of water in every direction -- as well in the teeth of the wind as otherwise. Of foam there was little except in the immediate vicinity of the rocks.</p>

<p>"The island in the distance," resumed the old man, "is called by the Norwegians Vurrgh. The one midway is Moskoe. That a mile to the northward is Ambaaren. Yonder are Islesen, Hotholm, Keildhelm, Suarven, and Buckholm. Farther off -- between Moskoe and Vurrgh -- are Otterholm, Flimen, Sandflesen, and Stockholm. These are the true names of the places -- but why it has been thought necessary to name them at all, is more than either you or I can understand. Do you hear anything ? Do you see any change in the water ?"</p>

<p>We had now been about ten minutes upon the top of Helseggen, to which we had ascended from the interior of Lofoden, so that we had caught no glimpse of the sea until it had burst upon us from the summit. As the old man spoke, I became aware of a loud and gradually increasing sound, like the moaning of a vast herd of buffaloes upon an American prairie; and at the same moment I perceived that what seamen term the chopping character of the ocean beneath us, was rapidly changing into a current which set to the eastward. Even while I gazed, this current acquired a monstrous velocity. Each moment added to its speed -- to its headlong impetuosity. In five minutes the whole sea, as far as Vurrgh, was lashed into ungovernable fury ; but it was between Moskoe and the coast that the main uproar held its sway. Here the vast bed of the waters, seamed and scarred into a thousand conflicting channels, burst suddenly into phrensied convulsion -- heaving, boiling, hissing -- gyrating in gigantic and innumerable vortices, and all whirling and plunging on to the eastward with a rapidity which water never elsewhere assumes except in precipitous descents. </p>

<?php 
    include ('/home/tgorczynski1/public_html/dmit2025/includes-site/footer.php');    
    
?>